name: context-demo
on: 
  workflow_dispatch:
    inputs:
        descp:
          description: 'enter the word you want to print'
          type: text
          required: true
          default: 'hello'
env:
  firstName: 'Aravind'
  lastname : 'R'
  
jobs:
  context-demo:
      runs-on: ${{matrix.os}}
      strategy:
        matrix:
          os: [ubuntu-latest]
      steps:
        - run: echo ${{github.actor}}
        
        
           
    
     
            
          
